import React from "react";
import { useNavigate } from "react-router-dom";
import { Footer } from "./commonSections/Footer";

//if animation, in footer should pass prop absolute

export const SpecifyOrAutoRequirements = ({ disabled }) => {
  const navigate = useNavigate();
  return (
    <div>
      <div className="flex flex-col items-center   xl:mt-[100px]  px-[20px] sm:px-[45px]">
        <div
          onClick={() => navigate(disabled ? "" : "/autoGenerateDesign")}
          className="flex mb-[40px] items-center justify-center text-[22px] font-bold cursor-pointer text-[#1F2B37] rounded-full bg-[#77F2A1] w-[185px] h-[50px]"
        >
          Next
        </div>
        <div className="text-white text-center lg:text-left mb-[80px] xl:mb-[250px] text-[22px]">
          I’d like an autogenerated layout (based on my sector’s benchmarking)'
        </div>
      </div>
      <Footer />
    </div>
    // <div className="section !justify-start">
    //   <div className=" bg-white  px-[20px] sm:px-[45px] text-[#4F76F6] pt-[50px] pb-[60px] sm:pb-[140px]">
    //     <div className="text-[34px] sm:text-[36px] lg:text-[38px] xl:text-[40px] mb-[10px] font-bold ">
    //       Do you know your requirements?
    //     </div>
    //     <div className="text-[#4F76F6] text-[22px] font-bold mb-[35px]">
    //       Choose Yes or No below
    //     </div>
    //     <div className="text-[#1F2B37] text-[22px]">
    //       <div className="flex flex-col lg:flex-row  mb-[40px] lg:mb-[20px] lg:items-center">
    //         <div
    //           onClick={() => navigate("/autoGenerateDesign")}
    //           className="flex mb-[10px] lg:mb-0  mr-[25px] items-center justify-center text-[22px] font-bold cursor-pointer text-[#1F2B37] rounded-full bg-[#77F2A1] w-[185px] h-[50px]"
    //         >
    //           Yes
    //         </div>
    //         <div>I’d like to specify my own requirements</div>
    //       </div>
    //       <div className="flex flex-col lg:flex-row lg:items-center  ">
    //         <div
    //           onClick={() => {}}
    //           className="flex mb-[10px] lg:mb-0  mr-[25px] items-center justify-center text-[22px] font-bold cursor-pointer text-[#1F2B37] rounded-full bg-[#77F2A1] w-[185px] h-[50px]"
    //         >
    //           No
    //         </div>
    //         <div>
    //           I’d like an autogenerated layout (based on my sector’s
    //           benchmarking)
    //         </div>
    //       </div>
    //     </div>
    //   </div>
    //   <Footer />
    // </div>
  );
};
